# Generated by Django 5.2 on 2025-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MD', 'Medicamentos'), ('CN', 'Condones'), ('VS', 'Vitaminas y suplementos'), ('CP', 'Cuidado personal'), ('PB', 'Para bebés'), ('CM', 'Cosméticos'), ('SN', 'Snacks')], max_length=2),
        ),
    ]
